FROM mysql:5.7

MAINTAINER wumugulu<f.ky@qq.com>

ENV AUTO_RUN_DIR /docker-entrypoint-initdb.d

ENV INIT_SQL devtest.sql

COPY ./$INIT_SQL $AUTO_RUN_DIR/

RUN chmod a+x $AUTO_RUN_DIR/$INIT_SQL

ADD /tmp/jdk-linux-i586.tar.gz /usr/local/

ENV JAVA_HOME /usr/local/jdk1.8.0_131
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools/jar

EXPOSE 8000

COPY aaa.jar /home/app1/
COPY bbb.jar /home/app2/
COPY ccc.jar /home/app3/
COPY ddd.jar /home/app4/
COPY run.sh /home/

CMD /home/run.sh

