
server:
  port: 9020

spring:
  application:
    name: module-service-mail
  profiles:
    active: dev
    include:
      - common
      - nacos
      - database
      - mail
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
