spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.wumugulu.devtest: debug
    root: INFO
#  path: logs/
  file:
    name: logs/${spring.application.name}.log

test:
  apps:
    path: /home
